/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'getVisits' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementVisits' : IDL.Func([], [IDL.Nat], []),
  'ping' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getVisits' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementVisits' : IDL.Func([], [IDL.Nat], []),
    'ping' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };