/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmployeeCount { 'name' : string, 'count' : bigint }
export interface SearchRecord { 'name' : string, 'timestamp' : bigint }
export interface Stats {
  'lastVisitTime' : bigint,
  'totalVisits' : bigint,
  'totalSearches' : bigint,
}
export interface _SERVICE {
  'getMostSearched' : ActorMethod<[bigint], Array<EmployeeCount>>,
  'getRecentSearches' : ActorMethod<[bigint], Array<SearchRecord>>,
  'getStats' : ActorMethod<[], Stats>,
  'getVisits' : ActorMethod<[], bigint>,
  'incrementVisits' : ActorMethod<[], bigint>,
  'recordSearch' : ActorMethod<[string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];